changes some files to prepare for deploy on production mode

diff --git a/.github/workflows/buildAndDeploy.yml b/.github/workflows/buildAndDeploy.yml
--- a/.github/workflows/buildAndDeploy.yml
+++ b/.github/workflows/buildAndDeploy.yml
@@ -27,6 +27,11 @@ jobs:
         
     - name: Build and deploy
       run: |
-        docker compose down || true
-        
-        docker compose up -d
+         echo "🛑 Stopping and removing old containers..."
+         docker compose down || echo "No running containers to stop."
+
+         echo "🔄 Building and starting new containers..."
+         docker compose up --build -d || { echo "❌ Deployment failed! Check logs."; exit 1; }
+         echo "✅ Checking if services are running..."
+         sleep 10  # Give some time for services to start
+         docker compose ps
