added commond to generate ssl certificate

diff --git a/.github/workflows/buildAndDeploy.yml b/.github/workflows/buildAndDeploy.yml
--- a/.github/workflows/buildAndDeploy.yml
+++ b/.github/workflows/buildAndDeploy.yml
@@ -52,12 +52,14 @@ jobs:
         sudo chmod 666 /var/run/docker.sock
         
     - name: Build and deploy
+      - name: Build and deploy
       run: |
-         echo "Stopping and removing old containers..."
-         docker compose down || echo "No running containers to stop."
-
-         echo "Building and starting new containers..."
-         docker compose up --build -d || { echo "❌ Deployment failed! Check logs."; exit 1; }
-         echo "Checking if services are running..."
-         sleep 10  # Give some time for services to start
-         docker compose ps
+        echo "Stopping containers while preserving volumes..."
+        docker compose stop || echo "No running containers to stop."
+        
+        echo "Building and starting new containers..."
+        docker compose up --build -d || { echo "❌ Deployment failed! Check logs."; exit 1; }
+        
+        echo "Checking if services are running..."
+        sleep 10  # Give some time for services to start
+        docker compose ps
